--- 
name: build
on: [push, pull_request]
jobs:
  std_tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -r requirements-genie.txt

      - name: Run black
        run: |
          black --check .

      - name: Run linter
        run: |
          pylama .

      - name: Run Tests
        run: |
          py.test -v -s tests/test_import_netmiko.py
          py.test -v -s tests/unit/test_base_connection.py
          py.test -v -s tests/unit/test_utilities.py
          py.test -v -s tests/unit/test_ssh_autodetect.py
  integration-test:
    name: integration test
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2
      - name: Download released earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.5.7/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: netmiko integration test
        run: earthly -P --ci +integration-test

